/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easyNatura.view;

import easyNatura.controller.MenuController;

/**
 *
 * @author pedro
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private final MenuController controller;
    
    public Menu() {
        initComponents();
        controller = new MenuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cliente = new javax.swing.JMenu();
        cadastrarCliente = new javax.swing.JMenuItem();
        venda = new javax.swing.JMenu();
        efetuarVenda = new javax.swing.JMenuItem();
        listarVendas = new javax.swing.JMenuItem();
        estoque = new javax.swing.JMenu();
        cadastrarProduto = new javax.swing.JMenuItem();
        listarProdutos = new javax.swing.JMenuItem();
        Funcionario = new javax.swing.JMenu();
        cadastrarFuncionario1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyNatura/view/imagens/imagem-base1.png"))); // NOI18N

        cliente.setText("cliente");

        cadastrarCliente.setForeground(java.awt.Color.black);
        cadastrarCliente.setText("Cadastrar Cliente");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        cliente.add(cadastrarCliente);

        jMenuBar1.add(cliente);

        venda.setText("venda");

        efetuarVenda.setForeground(java.awt.Color.black);
        efetuarVenda.setText("Efetuar Venda");
        efetuarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarVendaActionPerformed(evt);
            }
        });
        venda.add(efetuarVenda);

        listarVendas.setForeground(java.awt.Color.black);
        listarVendas.setText("Listar Vendas");
        listarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarVendasActionPerformed(evt);
            }
        });
        venda.add(listarVendas);

        jMenuBar1.add(venda);

        estoque.setText("estoque");

        cadastrarProduto.setForeground(java.awt.Color.black);
        cadastrarProduto.setText("Cadastrar Produto");
        cadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProdutoActionPerformed(evt);
            }
        });
        estoque.add(cadastrarProduto);

        listarProdutos.setForeground(java.awt.Color.black);
        listarProdutos.setText("Listar Produtos");
        listarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProdutosActionPerformed(evt);
            }
        });
        estoque.add(listarProdutos);

        jMenuBar1.add(estoque);

        Funcionario.setText("Funcionário");

        cadastrarFuncionario1.setForeground(java.awt.Color.black);
        cadastrarFuncionario1.setText("Cadastrar Funcionário");
        cadastrarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionario1ActionPerformed(evt);
            }
        });
        Funcionario.add(cadastrarFuncionario1);

        jMenuBar1.add(Funcionario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        controller.iniciaCadCliente();
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void efetuarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarVendaActionPerformed
        controller.iniciaEfetuarVenda();
        // TODO add your handling code here:
    }//GEN-LAST:event_efetuarVendaActionPerformed

    private void listarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarVendasActionPerformed
        controller.iniciaListarVendas();
        // TODO add your handling code here:
    }//GEN-LAST:event_listarVendasActionPerformed

    private void cadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProdutoActionPerformed
        controller.iniciaCadProduto();
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarProdutoActionPerformed

    private void listarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProdutosActionPerformed
        controller.iniciaListarProdutos();
        // TODO add your handling code here:
    }//GEN-LAST:event_listarProdutosActionPerformed

    private void cadastrarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionario1ActionPerformed
        controller.inciaCadFunc();
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarFuncionario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Funcionario;
    private javax.swing.JMenuItem cadastrarCliente;
    private javax.swing.JMenuItem cadastrarFuncionario1;
    private javax.swing.JMenuItem cadastrarProduto;
    private javax.swing.JMenu cliente;
    private javax.swing.JMenuItem efetuarVenda;
    private javax.swing.JMenu estoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listarProdutos;
    private javax.swing.JMenuItem listarVendas;
    private javax.swing.JMenu venda;
    // End of variables declaration//GEN-END:variables
}
