/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easyNatura.view;

import easyNatura.controller.MenuController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author pedro
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private final MenuController controller;
    
    public Menu() {
        initComponents();
        controller = new MenuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelData = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cliente = new javax.swing.JMenu();
        cadastrarCliente = new javax.swing.JMenuItem();
        alterarDados = new javax.swing.JMenuItem();
        venda = new javax.swing.JMenu();
        efetuarVenda = new javax.swing.JMenuItem();
        listarVendas = new javax.swing.JMenuItem();
        estoque = new javax.swing.JMenu();
        cadastrarProduto = new javax.swing.JMenuItem();
        listarProdutos = new javax.swing.JMenuItem();
        Funcionario = new javax.swing.JMenu();
        cadastrarFuncionario1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelData.setFont(new java.awt.Font("Tlwg Typist", 1, 18)); // NOI18N
        jLabelData.setForeground(java.awt.Color.white);
        getContentPane().add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 120, 20));

        jLabelHora.setFont(new java.awt.Font("Tlwg Typist", 1, 18)); // NOI18N
        jLabelHora.setForeground(java.awt.Color.white);
        getContentPane().add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 100, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyNatura/view/imagens/fundo.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cliente.setText("Cliente");

        cadastrarCliente.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        cadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyNatura/view/imagens/user.png"))); // NOI18N
        cadastrarCliente.setText("Cadastrar");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        cliente.add(cadastrarCliente);

        alterarDados.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        alterarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyNatura/view/imagens/copywriter.png"))); // NOI18N
        alterarDados.setText("Alterar Dados");
        alterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDadosActionPerformed(evt);
            }
        });
        cliente.add(alterarDados);

        jMenuBar1.add(cliente);

        venda.setText("Venda");

        efetuarVenda.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        efetuarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyNatura/view/imagens/venda-ico.png"))); // NOI18N
        efetuarVenda.setText("Efetuar Venda");
        efetuarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarVendaActionPerformed(evt);
            }
        });
        venda.add(efetuarVenda);

        listarVendas.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        listarVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyNatura/view/imagens/listar-ico.png"))); // NOI18N
        listarVendas.setText("Listar Vendas");
        listarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarVendasActionPerformed(evt);
            }
        });
        venda.add(listarVendas);

        jMenuBar1.add(venda);

        estoque.setText("Estoque");

        cadastrarProduto.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        cadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyNatura/view/imagens/cadastrar-produtos-ico.png"))); // NOI18N
        cadastrarProduto.setText("Cadastrar Produto");
        cadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProdutoActionPerformed(evt);
            }
        });
        estoque.add(cadastrarProduto);

        listarProdutos.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        listarProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyNatura/view/imagens/listar-produtos-ico.png"))); // NOI18N
        listarProdutos.setText("Listar Produtos");
        listarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProdutosActionPerformed(evt);
            }
        });
        estoque.add(listarProdutos);

        jMenuBar1.add(estoque);

        Funcionario.setText("Funcionário");

        cadastrarFuncionario1.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        cadastrarFuncionario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyNatura/view/imagens/add-funcionario-ico.png"))); // NOI18N
        cadastrarFuncionario1.setText("Cadastrar Funcionário");
        cadastrarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionario1ActionPerformed(evt);
            }
        });
        Funcionario.add(cadastrarFuncionario1);

        jMenuBar1.add(Funcionario);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        controller.iniciaCadCliente();
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void efetuarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarVendaActionPerformed
        controller.iniciaEfetuarVenda();
        // TODO add your handling code here:
    }//GEN-LAST:event_efetuarVendaActionPerformed

    private void listarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarVendasActionPerformed
        controller.iniciaListarVendas();
        // TODO add your handling code here:
    }//GEN-LAST:event_listarVendasActionPerformed

    private void cadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProdutoActionPerformed
        controller.iniciaCadProduto();
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarProdutoActionPerformed

    private void listarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProdutosActionPerformed
        controller.iniciaListarProdutos();
        // TODO add your handling code here:
    }//GEN-LAST:event_listarProdutosActionPerformed

    private void cadastrarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionario1ActionPerformed
        controller.inciaCadFunc();
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarFuncionario1ActionPerformed

    private void alterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDadosActionPerformed
        controller.iniciaAltDados();
    }//GEN-LAST:event_alterarDadosActionPerformed

    
    class hora implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar agora = Calendar.getInstance();
            jLabelHora.setText(String.format("%1$tH:%1$tM:%1$tS",agora));
        }
    }
    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       // TODO add your handling code here:
        
        // DATA
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jLabelData.setText(formato.format(dataSistema));
        
        // HORA
        Timer timer = new Timer(1000, new hora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Funcionario;
    private javax.swing.JMenuItem alterarDados;
    private javax.swing.JMenuItem cadastrarCliente;
    private javax.swing.JMenuItem cadastrarFuncionario1;
    private javax.swing.JMenuItem cadastrarProduto;
    private javax.swing.JMenu cliente;
    private javax.swing.JMenuItem efetuarVenda;
    private javax.swing.JMenu estoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listarProdutos;
    private javax.swing.JMenuItem listarVendas;
    private javax.swing.JMenu venda;
    // End of variables declaration//GEN-END:variables
}
